# Generated by Django 5.2.17 on 2026-08-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('company_size', models.CharField(blank=True, choices=[('MICRO', 'Micro (< 10 employés)'), ('SMALL', 'Petite (10 à 49 employés)'), ('MEDIUM', 'Moyenne (50 à 249 employés)'), ('LARGE', 'Grande (250 employés et plus)')], max_length=10)),
                ('country', models.CharField(default='Maroc', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
    ]
