# Generated by Django 5.2.17 on 2026-08-25 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('probability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_score', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], editable=False, max_length=10)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identifié'), ('IN_TREATMENT', 'En traitement'), ('MITIGATED', 'Atténué'), ('ACCEPTED', 'Accepté')], default='IDENTIFIED', max_length=20)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='audits.audit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='questionnaires.category')),
                ('source_answer', models.ForeignKey(blank=True, help_text="Réponse à l'origine de ce risque, si généré automatiquement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_risks', to='audits.answer')),
            ],
            options={
                'verbose_name': 'Risque',
                'verbose_name_plural': 'Risques',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='RiskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=255)),
                ('risk_description', models.TextField(blank=True)),
                ('default_probability', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('default_impact', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_templates', to='questionnaires.question')),
                ('trigger_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_templates', to='questionnaires.answerchoice')),
            ],
            options={
                'verbose_name': 'Modèle de risque',
                'verbose_name_plural': 'Modèles de risque',
                'unique_together': {('question', 'trigger_choice')},
            },
        ),
    ]
