# Generated by Django 5.2.17 on 2026-08-28 17:45

import apps.audits.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'docx', 'xlsx']), apps.audits.models.validate_evidence_size]),
        ),
    ]
