# Generated by Django 5.2.17 on 2026-08-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0001_initial'),
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Niveau de maturité',
                'verbose_name_plural': 'Niveaux de maturité',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='audits.audit')),
                ('category', models.ForeignKey(blank=True, help_text="Laisser vide pour le score global de l'audit.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='questionnaires.category')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['audit', 'category__order'],
            },
        ),
    ]
